-   config:
        base_url: ${ENV(host)}
        name: 护理看板配置
        variables:
            k1: ${ENV(out_k1)}
            k2: ${ENV(in_k2)}
            orgId: ${ENV(orgId)}
            areaId: ${ENV(in_k3)}
            locationId: 99897828609
            org_areaid: 1-99897828607-XN3142

-   test:
        api: api/token.yml
        name: 登录获取token

-   test:
        api: api/setting.yml
        name: 登录设置

-   test:
        api: api/user_info.yml
        name: 切换登录院区部门

-   test:
        name: ' 通用查询系统参数'
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json:
                deptSystemParamList: ["900076"]
            method: POST
            url: /app-station-manage/orderCommon/listSystemParam
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 获取护理项目来源字典
        request:
            headers:
                Authorization: ${get_token($token)}
                k1: $k1
                k2: $areaId
            method: GET
            url: /app-nurse-station/board/nurse/task/item/source
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 查询药物治疗信息
        request:
            headers:
                Authorization: ${get_token($token)}
                k1: $k1
                k2: $areaId
            method: GET
            url: /app-medication-manage/medication/usage/listPrintClass
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 根据参数查询药品与诊疗项目
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json:
                orderType: 2
                searchText: /
            method: POST
            url: /app-sys-manage/clinicalPathwayOrder/itemNameFuzzySearch
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 获取护理任务类型字典
        request:
            headers:
                Authorization: ${get_token($token)}
                k1: $k1
                k2: $areaId
            method: GET
            url: /app-nurse-station/board/nurse/task/type
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 获取用户信息
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json: {}
            method: POST
            url: /app-portal/user/info
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 获取机构系统参数(查不到返回'')
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json:
                parameterCode: 30000004
            method: POST
            url: /app-sys-manage/param/getOrgSystemParam
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
        -   eq:
            - content.body
            - '2'
-   test:
        name: 查询用户信息
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json: {}
            method: POST
            url: /app-portal/permission/query/user/menu
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 首页显示模板列表查询
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json: {}
            method: POST
            url: /app-portal/stationmanage/stationConfig/list/getHomepage
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 通过任务类型编码查询任务
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json:
                taskTypeCode: FH0352.02
            method: POST
            url: /app-nurse-station/board/nurse/task/listByTaskTypeCode
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
-   test:
        name: 保存护理任务，新增/修改通用
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json:
                customize: ''
                enable: true
                id: null
                pinyin: ZDHCSHL
                sortNo: ${get_number(6)}
                taskName: 自动化测试护理
                taskTypeCode: FH0352.02
                wubi: TFWIYRG
            method: POST
            url: /app-nurse-station/board/nurse/task/save
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success
        -   eq:
            - content.body
            - true
-   test:
        name: 通过任务类型编码查询任务
        request:
            headers:
                Authorization: ${get_token($token)}
                Content-Type: application/json; charset=UTF-8
                k1: $k1
                k2: $areaId
            json:
                taskTypeCode: FH0352.02
            method: POST
            url: /app-nurse-station/board/nurse/task/listByTaskTypeCode
        validate:
        -   eq:
            - content.code
            - 2000
        -   eq:
            - content.message
            - success


-   test:
        name: 查询某个病区的待安床病人列表
        request:
            headers:
                Authorization: ${get_token($token)}
                k1: $k1
                k2: $areaId
            method: GET
            url: /app-nurse-station/patient/wait/list
        teardown_hooks:
          - ${reload_dict()}